http_stub_example_producer:
  build: .
  ports:
    - "3000:3000"
  volumes:
    - .:/root/app

http_stub_example:
  build: ../http_stub_example
  ports:
    - "5000:5000"
  volumes:
    - ../http_stub_example:/root/app
